name: Run Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Change this to the version you need
        extensions: mbstring, intl, pdo, pdo_mysql

    - name: Get composer cache directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --ansi

    - name: Generate application key
      run: php artisan key:generate

    - name: Create .env file
      run: |
        cp .env.example .env
        php artisan config:cache
        php artisan config:clear

    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_HOST: 127.0.0.1
      run: php artisan migrate

    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_HOST: 127.0.0.1
      run: vendor/bin/phpunit
